version: '3.8'

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser"]
      interval: 10s
      timeout: 5s
      retries: 5