version: '3.8'

services:
  # The Go application container
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp
    ports:
      - "8080:8080"  # Expose port 8080 on the host
    environment:
      - DB_HOST=postgres  # The name of the PostgreSQL service in Docker Compose
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_PORT=5432
    depends_on:
      - postgres   # Ensure postgres starts before the Go app

  # PostgreSQL container
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"   # Expose port 5432 for PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Persist database data between container restarts

volumes:
  postgres_data:
    driver: local
